filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /mnt/logs/*.log
  exclude_files: [ '\.gz$' ]
  tags: [ "magento-log" ]
  multiline.type: pattern
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
  host: "https://log-asus.smartosc-monitoring.com:443"
  ssl.verification_mode: none
output.logstash:
  hosts: ["logstash:5044"]
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
